### ISSUE TITLE
DOCS - Cronograma: Milestones

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#10]
Criar algum documento para facilitar observar as entregas da disciplina. Deve ser feita em conjunto com a Issue #9.

**Comment by ananorberto** [comment]
Fiz as últimas alterações no cronograma ontem. Acredito que o @samuel-sato tenha criado o PR, Solicito revisão.
