### ISSUE TITLE
DOCS - DAS implementação

### ISSUE THREAD

**Issue by kaua-pt** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#119]
## Descrição
Produzir o DAS implementação

## Tarefas
- [x] Produzir o DAS implementação

## Critérios de aceitação
Das produzido detalhadamente

**Comment by Mylena-angelica** [comment]
Documento criado na branch 119-docs-das-implementação.
[Link do documento](https://github.com/UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon/blob/119-docs-das-implementa%C3%A7%C3%A3o/docs/ArquiteturaReutilizacao/arquiteturaDeSoftware/das_implementa%C3%A7%C3%A3o.md)
