### ISSUE TITLE
DOCS - Elicitação dos requisitos 

### ISSUE THREAD

**Issue by kaua-pt** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#2]
# Descrição
Realizar a elicitação dos requisitos através de técnicas especificas

# Técnicas
- [x] Rich Picture
- [x] 5W2H
- [x] Brainstorming
- [x] Mapa mental
- [x] Entrevista 
- [x] Storyboard
- [x] Plano de risco

# Critérios de aceitação
Tecnicas elicitadas de forma correta e com o documento na pasta ./base/elicitação

**Comment by Mylena-angelica** [comment]
A técnica 5W2H já está feita. Só é necessário revisão

**Comment by kaua-pt** [comment]
Artefato de entrevista completo. Solicito revisão

**Comment by Mylena-angelica** [comment]
Meu RP foi adicionado nessa branch na pasta "assets"

**Comment by Beatrizvn** [comment]
Artefato Mapa mental completo

**Comment by ananorberto** [comment]
Rich picture adicionada na branch `2-docs-elicitação-dos-requisitos` na pasta `assets`.

**Comment by Mylena-angelica** [comment]
Check list dos rich pictures que estão na assests:

- [x] Ana Beatriz
- [ ] Arthur
- [ ] Augusto
- [ ] Beatriz
- [ ] Bruno
- [ ] Gabriel
- [ ] Guilherme
- [x] Kauã
- [x] Mylena
- [ ] Samuel

A medida que forem adicionando o arquivo, marcar seu nome no checklist

**Comment by Mylena-angelica** [comment]
Documentação de plano de risco já está na branch. Necessita de revisão

**Comment by ArthurFerreiraRodrigues** [comment]
Estou realizando a revisão dos itens já feitos. Revisões realizadas:

- [ ] Rich Picture
- [ ] 5W2H
- [ ] Brainstorming
- [ ] Mapa mental
- [ ] Entrevista 
- [ ] Storyboard
- [ ] Plano de risco

**Comment by ArthurFerreiraRodrigues** [comment]
> A técnica 5W2H já está feita. Só é necessário revisão

Documento 100%. Muito bom 👍

**Comment by ArthurFerreiraRodrigues** [comment]
@guilherme-puida 

Documento de brainstorm revisado. Nenhum erro, reformulei algumas frases e adicionei a referência que estava faltando.

**Comment by ArthurFerreiraRodrigues** [comment]
@kaua-pt https://github.com/UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon/issues/2#issuecomment-1707448114
> Artefato de entrevista completo. Solicito revisão

Artefato de entrevista revisado. Diversas correções gramaticais realizadas. Fora isso, conteúdo correto.

**Comment by ArthurFerreiraRodrigues** [comment]
@Beatrizvn / @ananorberto https://github.com/UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon/issues/2#issuecomment-1712499765
> Artefato Mapa mental completo. Já pode ser feito a revisão @ananorberto .

Apesar de já ter sido revisado, dei uma olhada novamente. Estava tudo 100%, só adicionei 2 espaços que estavam faltando após os ':' na legenda das tabelas. Boa 👍

**Comment by ArthurFerreiraRodrigues** [comment]
@ananorberto 

Documento do StoryBoard 100% 👍

**Comment by ArthurFerreiraRodrigues** [comment]
@Mylena-angelica https://github.com/UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon/issues/2#issuecomment-1718213753
> Documentação de plano de risco já está na branch. Necessita de revisão

Documento de Plano de Risco revisado. Conteúdo 100% e alguns erros gramaticais/escrita foram corrigidos.
