### ISSUE TITLE
DOCS - Metodologias e ferramentas utilizadas

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#63]
Adicionar as metodologias e ferramentas utilizadas com o respectivo ícone e justificativa da escolha desta.

**Comment by ArthurFerreiraRodrigues** [comment]
Lembrar do discord, das reuniões de quarta, do chat de daily e do chat do repositório que é atualizado pelo webhook do @guilherme-puida

**Comment by ananorberto** [comment]
É melhor apenas 1 documento com Metodologias e ferramentas ou fazer separado?

**Comment by ArthurFerreiraRodrigues** [comment]
@ananorberto https://github.com/UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon/issues/63#issuecomment-1721894686

> É melhor apenas 1 documento com Metodologias e ferramentas ou fazer separado?

Acredito que seja junto no tópico de Detalhamento Metodológico.

![image](https://github.com/UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon/assets/69909375/b8302a98-c2a4-4b96-a864-64b85bea26c4)

**Comment by ananorberto** [comment]
Finalizado! falta apenas adicionar as informações da parte de `Testar`, como técnicas e ferramentas utilizadas.

**Comment by ArthurFerreiraRodrigues** [comment]
Documentação de Testar adicionada.
