### ISSUE TITLE
DOCS - Diagrama de Pacotes

### ISSUE THREAD

**Issue by kaua-pt** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#80]
## Descrição
Produzir o diagrama de pacotes

## Tarefas
- [ ] Produzir o diagrama de pacotes

## Critérios de aceitação
Diagramas feitos detalhadamente

**Comment by Mylena-angelica** [comment]
Nesse [link ](https://www.lucidchart.com/pages/pt/diagrama-de-pacotes-uml)tem algumas informações que podem ajudar na criação do diagrama.

E o diagrama será montado no [Lucid Chart.](https://lucid.app/lucidchart/f0a2748a-4b6a-4d24-b1f1-d8f17136f0d4/edit?viewport_loc=-10%2C-10%2C1707%2C759%2C0_0&invitationId=inv_edea634f-f5ca-4f8c-90b1-e977012aa695)

**Comment by Mylena-angelica** [comment]
Somente eu e o Kauã estamos com permissão de edição. Caso mais alguém do grupo queria, só me encaminhar o e-mail que eu adiciona lá

**Comment by Mylena-angelica** [comment]
A primeira versão do diagrama já está pronta.

Para a segunda versão iremos:

-  Adentrarem em pacotes de cunho mais interno;
- Nomear as dependências.

**Comment by kaua-pt** [comment]
Diagrama de pacotes feito, juntamente com o documento. Resta apenas produzir novas versões do mesmo

**Comment by Mylena-angelica** [comment]
Versão 3 do diagrama completo. Talvez será feita outra versão em razão do feedback da professora.

**Comment by kaua-pt** [comment]
Diagrama de pacotes quase finalizado
