### ISSUE TITLE
DOCS - Diagrama de Estados

### ISSUE THREAD

**Issue by guilherme-puida** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#84]

**Comment by Mylena-angelica** [comment]
Os diagramas de estado serão confeccionados no seguinte [link](https://lucid.app/lucidchart/f0a2748a-4b6a-4d24-b1f1-d8f17136f0d4/edit?viewport_loc=-11%2C-10%2C1993%2C759%2CrP5zvCyaz_BT&invitationId=inv_edea634f-f5ca-4f8c-90b1-e977012aa695). 
Somente os autores estão com permissão para editar, mas caso alguém do grupo queira acesso de editor, por favor solicitar.

**Comment by Mylena-angelica** [comment]
Diagrama de estados de pagamento finalizado
